<?php
/**
 * @copyright   Copyright © Avarda. All rights reserved.
 * @package     Avarda_CustomerInvoices
 */
/** @var $block \Avarda\CustomerInvoices\Block\CustomerInvoices */
$account = $block->getCustomerAccount();
?>
<a href="<?=$block->getUrl('avarda_customer/invoices')?>"><?=__('Back to list')?></a><br><br>
<div class="block my-invoice">
    <div class="block-content">
        <div class="table-wrapper">
            <table class="data table">
                <tr>
                    <td class="td-table">
                        <table class="data table">
                            <tr>
                                <td colspan="2">
                                    <div class="block-title">
                                        <strong><?=__('Account Details')?></strong>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 30%" class="col"><?=__('Due Date')?></td>
                                <td><?=$block->formatDate($account['dueDate'])?></td>
                            </tr>
                            <tr>
                                <td style="width: 30%" class="col"><?=__('Receiver')?></td>
                                <td><?=$account['receiver']?></td>
                            </tr>
                        </table>
                    </td>
                    <td class="td-table">
                        <table class="data table">
                            <tr>
                                <td>
                                    <div class="state <?=$block->getStateClass($account['state'])?>"><?=__($account['state'])?></div>
                                </td>
                                <td>
                                    <?php if ($block->needsToPay($account)): ?>
                                        <div class="actions-toolbar">
                                            <div class="primary">
                                                <form method="get" action="<?=$block->getUrl('avarda_customer/invoices/pay', ['id' => $account['id']])?>">
                                                    <button type="submit" title="<?=__('Pay Invoice')?>" class="action primary"><span><?=__('Pay Invoice')?></span></button>
                                                </form>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 30%" class="col"><?=__('Open balance')?></td>
                                <td><?=$block->getFormattedPrice($account['balance'])?></td>
                            </tr>
                            <tr>
                                <td style="width: 30%" class="col"><?=__('Minimum amount to pay')?></td>
                                <td><?=$block->getFormattedPrice($account['minimumAmountToPay'])?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="block my-invoice-details">
    <div class="block-title"><strong><?=__('Additional Details')?></strong></div>
    <div class="block-content">
        <div class="table-wrapper">
            <table class="data table">
                    <tr>
                        <td style="width: 30%" class="col"><?=__('Account Created')?></td>
                        <td><?=$block->formatDate($account['accountDate'])?></td>
                    </tr>
                    <tr>
                        <td style="width: 30%" class="col"><?=__('Total Amount')?></td>
                        <td><?=$block->getFormattedPrice($account['originalAmount'])?></td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td style="width: 30%" class="col"><?=__('Payment Reference')?></td>
                        <td><?=$account['paymentReference']?></td>
                    </tr>
                    <tr>
                        <td style="width: 30%" class="col"><?=__('Account Number')?></td>
                        <td><?=$account['bankAccount']?></td>
                    </tr>
                    <tr>
                        <td style="width: 30%" class="col"><?=__('Order Reference')?></td>
                        <td><?=implode(', ', $account['orderReference'])?></td>
                    </tr>
            </table>
        </div>
    </div>
</div>

<div class="block my-invoice-transactions">
    <div class="block-title"><strong><?=__('Transactions')?></strong></div>
    <div class="block-content">
        <div class="table-wrapper">
            <table class="data table">
                <caption class="table-caption"><?=__('Transactions')?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col"><?=__('Date')?></th>
                    <th scope="col" class="col"><?=__('Description')?></th>
                    <th scope="col" class="col"><?=__('Amount')?></th>
                </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                foreach ($account['transactions'] as $transaction):
                    $i++;
                    if ($i > 5) {
                        break;
                    }
                    ?>
                    <tr>
                        <td data-th="<?=__('Date')?>" class="col"><?=$block->formatDate($transaction['transactionDate'])?></td>
                        <td data-th="<?=__('Description')?>" class="col"><?=$block->escapeHtml($transaction['description'])?></td>
                        <td data-th="<?=__('Amount')?>" class="col"><?=$block->getFormattedPrice($transaction['amount'])?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
