<?php
/**
 * @copyright   Copyright © Avarda. All rights reserved.
 * @package     Avarda_CustomerInvoices
 */
/** @var $block \Avarda\CustomerInvoices\Block\CustomerInvoices */

$invoice = $block->getCustomerInvoice();
?>
<a href="<?=$block->getUrl('avarda_customer/invoices')?>">Back to list</a><br><br>
<div class="block">
    <div class="block-title"><strong><?=__('Invoice Details')?></strong></div>
    <div class="block-content">
        <div class="table-wrapper">
            <table class="data table">
                <tr>
                    <td style="width: 30%" class="col"><?=__('Invoice Created')?></td>
                    <td><?=$block->formatDate($invoice['accountDate'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Due Date')?></td>
                    <td><?=$block->formatDate($invoice['dueDate'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Total Amount')?></td>
                    <td><?=$block->getFormattedPrice($invoice['originalAmount'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Minimum amount to pay')?></td>
                    <td><?=$block->getFormattedPrice($invoice['minimumAmountToPay'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Balance')?></td>
                    <td><?=$block->getFormattedPrice($invoice['balance'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Status')?></td>
                    <td><?=__($invoice['state'])?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Payment Reference')?></td>
                    <td><?=$invoice['paymentReference']?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Receiver')?></td>
                    <td><?=$invoice['receiver']?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Account Number')?></td>
                    <td><?=$invoice['bankAccount']?></td>
                </tr>
                <tr>
                    <td style="width: 30%" class="col"><?=__('Order Reference')?></td>
                    <td><?=reset($invoice['orderReference'])?></td>
                </tr>
            </table>
        </div>
        <?php if ($block->needsToPay($invoice)): ?>
        <div class="actions-toolbar">
            <div class="primary">
                <form method="get" action="<?=$block->getUrl('avarda_customer/invoices/pay', ['id' => $invoice['id']])?>">
                    <button type="submit" title="<?=__('Pay')?>" class="action primary"><span><?=__('Pay')?></span></button>
                </form>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<div class="block">
    <div class="block-title"><strong><?=__('Transactions')?></strong></div>
    <div class="block-content">
        <div class="table-wrapper">
            <table class="data table">
                <caption class="table-caption"><?=__('Transactions')?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col"><?=__('Date')?></th>
                        <th scope="col" class="col"><?=__('Description')?></th>
                        <th scope="col" class="col"><?=__('Amount')?></th>
                    </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                foreach ($invoice['transactions'] as $transaction) :
                    $i++;
                    if ($i > 5) {
                        break;
                    }
                    ?>
                    <tr>
                        <td data-th="<?=__('Date')?>" class="col"><?=$block->formatDate($transaction['transactionDate'])?></td>
                        <td data-th="<?=__('Description')?>" class="col"><?=$block->escapeHtml($transaction['description'])?></td>
                        <td data-th="<?=__('Amount')?>" class="col"><?=$block->getFormattedPrice($transaction['amount'])?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
