<?php
/**
 * @copyright   Copyright © Avarda. All rights reserved.
 * @package     Avarda_CustomerInvoices
 */
/** @var $block \Avarda\CustomerInvoices\Block\CustomerInvoices */

$scriptUrl = $block->getPayFrameUrl();
$siteKey = $block->getAvardaSiteKey();
$locale = $block->getLocale();
?>

<div id="pay-frame"></div>

<script type="text/javascript">
    require(["Avarda_CustomerInvoices/js/pay-frame"], function (PayFrameLoader) {
        PayFrameLoader.loadPayFrame("<?= $scriptUrl ?>", "<?= $siteKey ?>", "<?= $locale ?>");
    });
</script>
