<?php
/**
 * @copyright   Copyright © Avarda. All rights reserved.
 * @package     Avarda_CustomerInvoices
 */
/** @var $block \Avarda\CustomerInvoices\Block\CustomerInvoices */
$token = $block->getPayToken();
$purchaseId = $token['purchaseId'] ?? '';
$jwtToken = $token['jwt'] ?? '';
?>
<div class="block">
    <div class="block-content">
        <?php
        if (!$token) {
            echo __('Error initializing the payment');
        }
        ?>
        <div id="avarda-checkout-iframe"></div>
    </div>
</div>
<a href="<?=$block->getUrl('avarda_customer/invoices')?>">Back to list</a>
<?php if ($token): ?>
<script>
    const CHECKOUT3_JS_BUNDLE = '<?= $block->getCheckOutClientScriptPath(); ?>';
    (function(e,t,n,a,s,c,o,i,r){e[a]=e[a]||function(){(e[a].q=e[a].q||[
    ]).push(arguments)};e[a].i=s;i=t.createElement(n);i.async=1
    ;i.src=o+"?v="+c+"&ts="+1*new Date;r=t.getElementsByTagName(n)[0]
    ;r.parentNode.insertBefore(i,r)})(window,document,"script",
        "avardaCheckoutInit","avardaCheckout","1.0.0",CHECKOUT3_JS_BUNDLE
    );
    let options = {
        rootElementId: "avarda-checkout-iframe",
        purchaseId: "<?= $purchaseId ?>",
        purchaseJwt: "<?= $jwtToken ?>",
        redirectUrl: '<?= $block->getUrl('avarda_customer/invoices') ?>',
        completedPurchaseCallback: function (avardaCheckoutInstance) {
            avardaCheckoutInstance.unmount();
            window.location.href = "<?= $block->getUrl('avarda_customer/invoices') ?>";
        },
        beforeSubmitCallback: function (data, avardaCheckoutInstance) {
            avardaCheckoutInstance.beforeSubmitContinue();
        },
        sessionTimedOutCallback: function (avardaCheckoutInstance) {
            avardaCheckoutInstance.unmount();
            options.purchaseId = undefined;
        }
    };
    avardaCheckoutInit(options);
</script>
<?php endif; ?>

